services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=emmannweb@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  frontend:
    depends_on:
      - backend
    image: docker.io/emmann/toyofront:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`fondationwilcoxtoyo.org`) || Host(`www.fondationwilcoxtoyo.org`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
  
  backend:
    depends_on:
       - database
    image: docker.io/emmann/toyoback:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      - "traefik.http.routers.backend.rule=Host(`fondationwilcoxtoyo.org`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.service=backend"
    restart: always
    env_file: .env
  database: 
    image: "mongo"
    restart: always
    container_name: mongo-db
    command: [--auth]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      # - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./mongodata:/mongodata
volumes:
  letsencrypt:
  mongodata:
   driver: local  # Persist MongoDB data locally

